### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for java.nio.ByteBuffer 

### ISSUE THREAD

**Issue by Fanom2813** [zeroed-tech/LibGDX-QR#4]
I'm getting this error ` java.lang.UnsatisfiedLinkError: No implementation found for java.nio.ByteBuffer ` here is the exception : 

```
2022-05-14 10:08:48.818 3063-3063/com.smartcabspro.driver E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.smartcabspro.driver, PID: 3063
    java.lang.UnsatisfiedLinkError: No implementation found for java.nio.ByteBuffer com.badlogic.gdx.utils.BufferUtils.newDisposableByteBuffer(int) (tried Java_com_badlogic_gdx_utils_BufferUtils_newDisposableByteBuffer and Java_com_badlogic_gdx_utils_BufferUtils_newDisposableByteBuffer__I)
        at com.badlogic.gdx.utils.BufferUtils.newDisposableByteBuffer(Native Method)
        at com.badlogic.gdx.utils.BufferUtils.newUnsafeByteBuffer(BufferUtils.java:519)
        at com.badlogic.gdx.graphics.glutils.VertexArray.<init>(VertexArray.java:57)
        at com.badlogic.gdx.graphics.Mesh.<init>(Mesh.java:187)
        at com.badlogic.gdx.graphics.Mesh.<init>(Mesh.java:158)
        at com.badlogic.gdx.graphics.g2d.PolygonSpriteBatch.<init>(PolygonSpriteBatch.java:133)
        at com.badlogic.gdx.graphics.g2d.PolygonSpriteBatch.<init>(PolygonSpriteBatch.java:111)
        at com.badlogic.gdx.graphics.g2d.PolygonSpriteBatch.<init>(PolygonSpriteBatch.java:97)
        at tech.zeroed.libgdxqr.QRGenerator.generate(QRGenerator.java:110)
        at com.smartcabspro.driver.ui.settings.SettingsFragment.generateQr(SettingsFragment.java:268)
        at com.smartcabspro.driver.ui.settings.SettingsFragment.onResume(SettingsFragment.java:243)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:3039)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:607)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:306)
        at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:745)
        at androidx.fragment.app.SpecialEffectsController$Operation.completeSpecialEffect(SpecialEffectsController.java:672)
        at androidx.fragment.app.DefaultSpecialEffectsController$SpecialEffectsInfo.completeSpecialEffect(DefaultSpecialEffectsController.java:776)
        at androidx.fragment.app.DefaultSpecialEffectsController.startAnimations(DefaultSpecialEffectsController.java:147)
        at androidx.fragment.app.DefaultSpecialEffectsController.executeOperations(DefaultSpecialEffectsController.java:120)
        at androidx.fragment.app.SpecialEffectsController.executePendingOperations(SpecialEffectsController.java:297)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2202)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:264)
        at android.app.ActivityThread.main(ActivityThread.java:7605)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

```

My code : 

 ```
private void generateQr() {
        QRGenerator generator = QRCode.CreateGenerator();
        generator.blockSize(10);
        generator.borderSize(1);
        generator.primaryColor(Color.BLACK);
        generator.secondaryColor(Color.WHITE);
        generator.setEyeBorderShape(QRGenerator.Shape.ARC);
        generator.setEyeInnerShape(QRGenerator.Shape.CIRCLE);
        generator.setInnerShape(QRGenerator.Shape.SQUARE);

        TextureRegion code = generator.generate("Zeroed.tech");
    }
```

What could be the issue ?

**Comment by zeroed-tech** [comment]
Not sure sorry, that's pretty deep into libgdxs code. It could be something is incompatible with the newer version of libgdx
